import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const initial = process.cwd();
const testDir = mkdtempSync(path.join(tmpdir(), 'dashboard-auth-test-'));
process.chdir(testDir);
process.env.WEBHOOK_SECRET = 'test-only-webhook-secret';
const { db } = await import('../server/db.js');
const { hashPassword, cookie } = await import('../server/auth.js');
const password = 'test-only-password-123456';
await db.prepare('INSERT INTO auth_users(username,password_hash) VALUES (?,?)').run('tester', await hashPassword(password));
const port = 23000 + Math.floor(Math.random() * 10000);
const base = `http://localhost:${port}`;
const child = spawn(process.execPath, [path.join(project, 'server/index.js')], { cwd: testDir, env: { ...process.env, PORT: String(port), NODE_ENV: 'test' }, stdio: ['ignore','pipe','pipe'] });
const call = (route, method='GET', body, token, origin) => fetch(base + '/api/' + route, { method, headers: { ...(body !== undefined ? {'Content-Type':'application/json'} : {}), ...(token ? {Cookie:token} : {}), ...(origin ? {Origin:origin} : {}) }, body: body !== undefined ? JSON.stringify(body) : undefined });
const login = () => call('login','POST',{username:'tester',password});
const token = r => r.headers.get('set-cookie').split(';')[0];
try {
  await new Promise((resolve,reject) => { const timeout=setTimeout(()=>reject(new Error('Server startup timeout')),10000); child.stdout.on('data', d => { if (String(d).includes('API em')) { clearTimeout(timeout); resolve(); } }); child.once('exit', code=>{clearTimeout(timeout);reject(new Error('Server stopped: '+code));}); });
  assert.equal((await call('data')).status,401);
  assert.equal((await call('clients','POST',{name:'blocked'})).status,401);
  assert.equal((await call('webhook-secret')).status,401);
  assert.equal((await call('data','GET',undefined,'session=forged')).status,401);
  assert.equal((await call('login','POST',{username:'tester',password},undefined,'https://evil.example')).status,403);
  assert.equal((await call('login','POST',{username:'wrong',password},undefined,'http://localhost:5180')).status,401);
  assert.equal((await call('login','POST',{username:'tester',password:'wrong'})).status,401);
  const first=await login(); assert.equal(first.status,200);
  assert.match(first.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);
  assert.equal(first.headers.get('cache-control'),'no-store');
  const firstToken=token(first);
  assert.equal((await call('data','GET',undefined,firstToken)).status,200);
  assert.equal((await call('logout','POST',{},firstToken)).status,200);
  assert.equal((await call('data','GET',undefined,firstToken)).status,401);
  const secondToken=token(await login()), thirdToken=token(await login());
  assert.equal((await call('change-password','POST',{currentPassword:password,newPassword:'short'},secondToken)).status,400);
  const newPassword='new-test-only-password-987654';
  const changed=await call('change-password','POST',{currentPassword:password,newPassword},secondToken); assert.equal(changed.status,200);
  assert.equal((await call('data','GET',undefined,secondToken)).status,401);
  assert.equal((await call('data','GET',undefined,thirdToken)).status,401);
  assert.equal((await call('data','GET',undefined,token(changed))).status,200);
  assert.equal((await login()).status,401);
  const newLogin=await call('login','POST',{username:'tester',password:newPassword});assert.equal(newLogin.status,200);
  const activeToken=token(newLogin);await db.prepare('UPDATE auth_sessions SET expires=0').run();
  assert.equal((await call('data','GET',undefined,activeToken)).status,401);
  const hash=(await db.prepare('SELECT password_hash FROM auth_users').get()).password_hash;
  assert.ok(!hash.includes(newPassword));
  for(let i=0;i<12;i++) await call('login','POST',{username:'tester',password:'wrong'});
  assert.equal((await login()).status,429);
  process.env.NODE_ENV='production'; assert.match(cookie('test'),/; Secure$/);
  console.log('PASS: private API, credential validation, CSRF, cookies, logout, password change, session expiry and rate limiting.');
} finally {
  child.kill(); await new Promise(resolve=>{if(child.exitCode!==null) resolve();else child.once('exit',resolve);});
  await db.close();process.chdir(initial);
  if (path.dirname(testDir) !== path.resolve(tmpdir()) || !path.basename(testDir).startsWith('dashboard-auth-test-')) throw new Error('Unexpected cleanup path');
  rmSync(testDir,{recursive:true,force:true});
}
